### ISSUE TITLE
" Add Card to Apple Pay" error shown though Card exists in Phone

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#70]
**Version**: "judokit-react-native": "3.0.1",

**Implementation**:

```

const applePayOptions: JudoApplePayConfiguration = {
        merchantId: AppConfig.JudoKit.merchantId,
        countryCode: 'GB',
        paymentSummaryItems: [
            {
                label: QUICK_CHECKOUT_STRINGS.PAY_FOODHUB,
                amount: isValidElement(total) && isValidString(total.value) ? total.value : '0.00'
            }
        ]
    };
    // 1. Create a Judo session by providing an authorization object (basic or session)
    const auth: JudoAuthorization = { token: AppConfig.JudoKit.token, secret: AppConfig.JudoKit.secret };
    const judoPay = new Judo(auth);

    // 3. Create a Judo configuration to setup your payment flow
    const amount: JudoAmount = {
        value: isValidElement(total) ? total.value : '0.00',
        currency: 'GBP'
    };

    const reference: JudoReference = {
        consumerReference: consumerRef,
        paymentReference: paymentReference(),
        metadata: metaData
    };

    const configuration: JudoConfiguration = {
        judoId: AppConfig.JudoKit.judoId,
        amount: amount,
        reference: reference,
        applePayConfiguration: applePayOptions
    };

    try {
        let response = yield judoPay.invokeApplePay(JudoTransactionMode.ServerToServer, configuration);
        yield handleResponse(false, response, null, cartID);
    } catch (e) {
        yield handleResponse(true, null, e);
    }
```

 I have used in a different app https://www.npmjs.com/package/judo-react-native and there was no such problems.

 
![IMG_1805](https://user-images.githubusercontent.com/30921040/96707092-0d6a2300-13b5-11eb-9e33-4fd9fc53c350.PNG)

**Similar Issue:**
https://community.revolut.com/t/apple-pay-add-a-card-that-is-accepted-by-this-app/27433/48

**Comment by radhakrishnant2s** [comment]
Please provide a resolution as this is a blocker for my team.

**Comment by mpetrenco** [comment]
@radhakrishnant2s I was wondering if this issue persists on the native iOS SDK as well or is it exclusive to the React Native build?

**Comment by radhakrishnant2s** [comment]
The RN library internally uses the JudoKit-iOS SDK only. Hence this would happen.

**Comment by mpetrenco** [comment]
That would depend. If the issue is present on React Native (which uses an older version of iOS), but not on native iOS, it would mean that there's either an issue with the RN wrapper code, or it's an issue that was fixed in the newer versions of the native SDK.

Anyways, thanks for opening this. We'll get back with more updates as soon as we start working on it.

**Comment by mpetrenco** [comment]
We released the 3.1.0 that hopefully will solve most RN problems. Regarding this issue, setting your `merchantCapabilities` to `JudoMerchantCapability.ThreeDS` might solve your problem.

**Comment by mpetrenco** [comment]
@radhakrishnant2s can you please confirm if this issue persists or was it fixed with the solution above?

**Comment by radhakrishnant2s** [comment]
This is resolved now
