### ISSUE TITLE
Apple pay window does not show  for the first time apple pay is initiated

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#72]
**Version used:**

2.1.0

On the first launch of the app and when the first time the apple pay is initiated, the apple pay does not 
show and the user canceled message is triggered.

On further attempts, this works without any problem.

**Comment by mpetrenco** [comment]
Please check out 3.1.0 and see if it persists: https://www.npmjs.com/package/judokit-react-native

**Comment by radhakrishnant2s** [comment]
Tried this latest version and got an error with apple pay. More details here https://github.com/Judopay/JudoKit-ReactNative/issues/82

**Comment by mpetrenco** [comment]
Issue was handled at #82

**Comment by selvamariappant2s** [comment]
It occurs in the 3.3.5 version of judokit-react-native

**Comment by PavithraPurushothaman-T2S** [comment]
Issue is happening now in version 3.3.7 of judokit-react-native also.
