### ISSUE TITLE
Run time error  while making payments in simulator irrespective of the result of the apple pay's result

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#82]
Tested in Simulator

**Version**:

judokit-react-native 3.1.0 

**Code**:

`showApplePay = () => {
        const total = '0.02';
        const consumerRef = '000';
        const metadata = new Map();
        const label = QUICK_CHECKOUT_STRINGS.PAY_FOODHUB_FALBACK;
        const userID = '';
        metadata.customerID = 'userID.toString()';
        const auth: JudoAuthorization = { token: AppConfig.JudoKit.token, secret: AppConfig.JudoKit.secret };
        const judo = new Judo(auth);
        const amount: JudoAmount = {
            value: isValidElement(total) && isValidString(total.value) ? total.value : '0.00',
            currency: 'GBP'
        };
        const reference: JudoReference = {
            consumerReference: consumerRef,
            paymentReference: paymentReference(),
            metadata
        };
        const applePayOptions: JudoApplePayConfiguration = {
            merchantId: AppConfig.JudoKit.merchantId,
            countryCode: 'GB',
            paymentSummaryItems: [
                {
                    label: label,
                    amount: isValidElement(total) && isValidString(total.value) ? total.value : '0.00'
                }
            ]
        };
        const configuration: JudoConfiguration = {
            judoId: AppConfig.JudoKit.judoId,
            amount: amount,
            reference: reference,
            applePayConfiguration: applePayOptions
        };
        judo.invokeApplePay(2, configuration)
            .then((response) => {
                showInfoMessage('works as expected');
            })
            .catch((error) => {
                showInfoMessage(error);
            });
    };`

**Error**:

The error happens irrespective of whether the operation succeeds or fails or cancelled by the user

<img width="480" alt="Screenshot 2020-11-19 at 11 05 13 AM" src="https://user-images.githubusercontent.com/30921040/99625858-1e12c500-2a57-11eb-9230-1ae9f2216401.png">

Invariant Violation: No callback found with cbID 138203 and callID 69101 for RNJudo.invokeApplePay - most likely the callback was already invoked. Args: '[{"code":"JUDO_ERROR","message":"Transaction cancelled","domain":"com.judo.error","userInfo":{"NSLocalizedFailureReason":"The user closed the transaction flow without completing the transaction.","NSLocalizedDescription":"The transaction was cancelled by the user."},"nativeStackIOS":["0 Foodhub 0x0000000106122ec7 RCTJSErrorFromCodeMessageAndNSError + 135","1 Foodhub 0x000000010609ed13 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179","2 Foodhub 0x0000000105fb105f __47-[RNJudo completionBlockWithResolve:andReject:]_block_invoke + 255","3 Foodhub 0x0000000105ee16f4 -[JudoKit(JPApplePayDelegate) applePayControllerDidCancelTransaction:] + 148","4 Foodhub 0x0000000105e6e5b6 -[JPApplePayController paymentAuthorizationViewControllerDidFinish:] + 118","5 PassKit 0x000000010ee781d4 __81-[PKPaymentAuthorizationViewController paymentAuthorizationCoordinatorDidFinish:]_block_invoke + 49","6 libdispatch.dylib 0x00000001127b18ac _dispatch_call_block_and_release + 12","7 libdispatch.dylib 0x00000001127b2a88 _dispatch_client_callout + 8","8 libdispatch.dylib 0x00000001127c0f23 _dispatch_main_queue_callback_4CF + 1152","9 CoreFoundation 0x000000010f575276 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9","10 CoreFoundation 0x000000010f56fb06 __CFRunLoopRun + 2685","11 CoreFoundation 0x000000010f56eb9e CFRunLoopRunSpecific + 567","12 GraphicsServices 0x0000000117359db3 GSEventRunModal + 139","13 UIKitCore 0x00000001277c3af3 -[UIApplication _run] + 912","14 UIKitCore 0x00000001277c8a04 UIApplicationMain + 101","15 Foodhub 0x0000000105ad5470 main + 112","16 libdyld.dylib 0x0000000112841415 start + 1"]}]'

**Comment by mpetrenco** [comment]
Hi @radhakrishnant2s, hopefully the dev support team reached you.
Based on the error, it looks like an error with the component hierarchy in the rendering method.

I did a sanity check on our SDK on a clean sample app, and everything works as expected. Our dev support team should have sent it to you.

Cheers!

**Comment by radhakrishnant2s** [comment]
Can you share the sample project and attach with your documentation too?

**Comment by mpetrenco** [comment]
Here you go. It has a step-by-step implementation approach that should be easy to follow:
[judo_sample.zip](https://github.com/Judopay/JudoKit-ReactNative/files/5573429/judo_sample.zip)

Usage: `npm install` - `npm run ios`

**Comment by radhakrishnant2s** [comment]
Ran that. Got the below error before getting dismissed

<img width="471" alt="Screenshot 2020-11-20 at 6 49 15 PM" src="https://user-images.githubusercontent.com/30921040/99804616-4981d680-2b61-11eb-9914-3a181b8a06fe.png">

**Comment by mpetrenco** [comment]
Can you please try 3.1.1 and see if this issue persists?
https://www.npmjs.com/package/judokit-react-native

**Comment by radhakrishnant2s** [comment]
Verified this in the simulator and it works

**Comment by mpetrenco** [comment]
Great! Glad it worked out 👍
Feel free to re-open the issue if any problems arise.

**Comment by radhakrishnant2s** [comment]
When I use 3.1.1 a strange error occurs in this project you had shared

npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: judo_sample@0.0.1
npm ERR! Found: react-native@0.63.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.61.5" from judokit-react-native@3.1.1
npm ERR! node_modules/judokit-react-native
npm ERR!   judokit-react-native@"3.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/radhakrishnan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/radhakrishnan/.npm/_logs/2020-12-08T05_14_42_954Z-debug.log
RKs-MacBook-Pro:ios radhakrishnan$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: judo_sample@0.0.1
npm ERR! Found: react-native@0.63.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.61.5" from judokit-react-native@3.1.1
npm ERR! node_modules/judokit-react-native
npm ERR!   judokit-react-native@"3.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/radhakrishnan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/radhakrishnan/.npm/_logs/2020-12-08T05_15_02_103Z-debug.log
RKs-MacBook-Pro:ios radhakrishnan$ 

please reopen it,

**Comment by selvamariappant2s** [comment]
The issue again occur in latest version JudoKit-ReactNative version 3.3.5
