### ISSUE TITLE
Error while building the android project

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#86]
**Project used:**

https://github.com/Judopay/JudoKit-ReactNative/issues/82#issuecomment-731232520

**Error log**

Checking the license for package Android SDK Build-Tools 29.0.2 in /Users/radhakrishnan/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 29.0.2 accepted.
Preparing "Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)".
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" ready.
Installing Android SDK Build-Tools 29.0.2 in /Users/radhakrishnan/Library/Android/sdk/build-tools/29.0.2
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" complete.
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" finished.
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.judokit.android:judokit-android:2.0.8.
     Searched in the following locations:
       - file:/Users/radhakrishnan/.m2/repository/com/judokit/android/judokit-android/2.0.8/judokit-android-2.0.8.pom
       - file:/Users/radhakrishnan/Downloads/judo_sample/node_modules/react-native/android/com/judokit/android/judokit-android/2.0.8/judokit-android-2.0.8.pom
       - file:/Users/radhakrishnan/Downloads/judo_sample/node_modules/jsc-android/dist/com/judokit/android/judokit-android/2.0.8/judokit-android-2.0.8.pom
       - https://dl.google.com/dl/android/maven2/com/judokit/android/judokit-android/2.0.8/judokit-android-2.0.8.pom
       - https://jcenter.bintray.com/com/judokit/android/judokit-android/2.0.8/judokit-android-2.0.8.pom
       - https://www.jitpack.io/com/judokit/android/judokit-android/2.0.8/judokit-android-2.0.8.pom
     Required by:
         project :app > project :judokit-react-native

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 31s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! judo_sample@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the judo_sample@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/radhakrishnan/.npm/_logs/2020-11-26T06_41_02_215Z-debug.log

**Comment by marcghelas** [comment]
@radhakrishnant2s have you added `maven { url 'http://dl.bintray.com/judopay/maven' }` to the top level build gradle file?
https://github.com/Judopay/JudoKit-ReactNative/blob/00639732416d6e6ed581fd4823cf39bcdaa3653f/sample-app/android/build.gradle#L32

Also don't forget to add the line 33 also since it's required for the android app to compile.

**Comment by radhakrishnant2s** [comment]
yes, I have it set it up

Below is the error message I received now:

> Task :judokit-react-native:compileReleaseKotlin FAILED
e: /Users/radhakrishnan/Development/customer_app_2.0/node_modules/judokit-react-native/android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt: (7, 31): Unresolved reference: FragmentActivity
e: /Users/radhakrishnan/Development/customer_app_2.0/node_modules/judokit-react-native/android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt: (8, 27): Unresolved reference: content
e: /Users/radhakrishnan/Development/customer_app_2.0/node_modules/judokit-react-native/android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt: (52, 9): Unresolved reference: LocalBroadcastManager
e: /Users/radhakrishnan/Development/customer_app_2.0/node_modules/judokit-react-native/android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt: (193, 51): Unresolved reference: FragmentActivity

**Comment by marcghelas** [comment]
@radhakrishnant2s I couldn't reproduce this build error, seems like AndroidX related stuff. A freshly built `react-native init` project works assuming the repositories that were mentioned earlier are included in gradle file. Try taking a look at the sample-app's gradle files, maybe there are some more dependencies you missed.
