### ISSUE TITLE
Apple pay does not succeed

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#87]
**Code used:**

`const amount: JudoAmount = {
    value: isValidElement(total) && isValidString(total.value) ? total.value : '0.00',
    currency: 'GBP'
};
const reference: JudoReference = {
    consumerReference: consumerRef,
    paymentReference: paymentReference(),
    metadata
};
const applePayOptions: JudoApplePayConfiguration = {
    merchantId: AppConfig.JudoKit.merchantId,
    countryCode: 'GB',
    paymentSummaryItems: [
        {
            label: label,
            amount: isValidElement(total) && isValidString(total.value) ? total.value : '0.00'
        }
    ]
};
const configuration: JudoConfiguration = {
    judoId: AppConfig.JudoKit.judoId,
    amount: amount,
    reference: reference,
    applePayConfiguration: applePayOptions
};
let response = yield judo.invokeApplePay(2, configuration);

        if (isValidElement(response) && isValidElement(response.result)) {
            yield* handlePaymentRedirection({ outcome: response.result.toLowerCase() });
        } else {
            yield* handlePaymentRedirection({ message: LOCALIZATION_STRINGS.SOMETHING_WENT_WRONG });
        }`

Output:
1. The amount never got deducted
2. The transaction was not recorded in judopay's dashboard
3. Below is the response from Judopay
****Response from judopay:****

{ amount: '0.02', 
orderDetails: { amount: 0 }, 
yourPaymentReference: 'xxx', cardDetails: { cardScheme: 'MasterCard', cardToken: 'xxxxx' }, 
createdAt: '2020-12-01T10:17:27.0640+05:30', 
currency: 'GBP', 
consumerResponse: { consumerReference: 'xxxxxx' }
 }

Earlier we were using library https://github.com/Judopay/JudoKit-ReactNative

export const JudoTransactionType = {
  payment: 0,
  preAuth: 1
};

The transaction type chosen was payment: 0.

Is this transaction type represented by the first parameter in the invokeApplePay function?

**Comment by mpetrenco** [comment]
Hi @radhakrishnant2s, I assume the issue is:

```
let response = yield judo.invokeApplePay(2, configuration);
```

The first parameter expects the `JudoTransactionMode`, which can be one of the following:
``` 
enum JudoTransactionMode {
    Payment,
    PreAuth,
    ServerToServer
}
```

In the code snippet above, you set **2** as the transaction mode, which maps to a server-to-server transaction. In a server-to-server transaction, we do not send any requests, but let the merchants do it on their side. We only provide the necessary configuration to do so.

It would be better to use types like so:

```
let response = yield judo.invokeApplePay(JudoTransactionMode.Payment, configuration);
```

instead of passing the integer value, to possibly avoid such issues in the future.

**Comment by radhakrishnant2s** [comment]
I have used both of them to try payments and both have failed
