### ISSUE TITLE
Unable to run the 3.1.1 version in the project shared for demo

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#88]
Reference project attached here:
https://github.com/Judopay/JudoKit-ReactNative/issues/82#issuecomment-731139595
@mpetrenco

When I use 3.1.1 a strange error occurs in this project you had shared

npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: judo_sample@0.0.1
npm ERR! Found: react-native@0.63.3
npm ERR! node_modules/react-native
npm ERR! react-native@"0.63.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.61.5" from judokit-react-native@3.1.1
npm ERR! node_modules/judokit-react-native
npm ERR! judokit-react-native@"3.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/zz/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/zz/.npm/_logs/2020-12-08T05_14_42_954Z-debug.log

**Comment by mpetrenco** [comment]
Hi @radhakrishnant2s, unfortunately I could not reproduce the issue. I'm able to successfully build and run the project.

<img width="469" alt="Screen Shot 2020-12-09 at 9 53 37 PM" src="https://user-images.githubusercontent.com/53521805/101758163-b1806880-3ae0-11eb-8757-077aea6f5dc7.png">

Try deleting your `node_modules`, cleaning your cache and use `yarn && yarn ios` again.
